# -*- coding: utf-8 -*-
"""전체과정.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TxK3L4_Sloyy95TQVW2aDpukIIY1FHt-

# 하나로 통합
"""

import os, csv, hashlib, math, struct, shutil, json, time, platform
import numpy as np
from collections import defaultdict, Counter
from typing import List, Tuple
from PIL import Image
from pathlib import Path


# ================== [ CONFIG ] ==================
# 1) 원본 데이터 루트(최상위 한 곳만 넣어도 하위 Train/Val/Test를 모두 재귀 탐색)
INPUT_ROOTS: List[str] = [
    r"/content/drive/MyDrive/Fit_Bool/Static_image/7. POC2_민성/Data_Set/Test/Malware"
]

# 2) 전처리 산출물(메타데이터) 저장 위치
OUT_DIR  = r"/content/drive/MyDrive/Fit_Bool/Static_image/7. POC2_민성/OUT_PreProcessing/Test/OUT_PreProcessing_Malware_csv_json"
os.makedirs(OUT_DIR, exist_ok=True)  # 출력 폴더 없으면 생성
OUT_CSV  = os.path.join(OUT_DIR, "manifest_pre_image.csv")
OUT_CFG  = os.path.join(OUT_DIR, "manifest_pre_image_config.json")

# 3) 정제본 EXE 복사본 생성 위치 (None이면 복사 생략, CSV/JSON만 생성)
CLEAN_ROOT = r"/content/drive/MyDrive/Fit_Bool/Static_image/7. POC2_민성/OUT_PreProcessing/Test/OUT_PreProcessing_Malware_Exe_1000"
# ===============================================

# 용량 필터 (상한 해제)
MIN_SIZE_BYTES = 1_024      # 1KB 미만 제외 (원하면 0으로)
MAX_SIZE_BYTES = None       # None이면 상한 없음 ✅

# 엔트로피/패킹
MAX_BYTES_FOR_ENTROPY = None   # None이면 파일 전체 사용 ✅
HIGH_ENTROPY_THRESH = 7.2      # 패킹 의심 기준

# 정책
SKIP_DUPLICATES = True    # 동일 sha256 중복은 첫 번째만 채택
REQUIRE_PE = True         # PE가 아니면 제외
ALLOW_DLLS = False        # DLL(IMAGE_FILE_DLL) 허용 여부
FILTER_SYMLINKS = True
FILTER_HIDDEN_FILES = True
HIDDEN_NAME_PREFIXES = (".", "._", "~")

# 정제본 복사 옵션
PRESERVE_STRUCTURE = True           # True: <split>/<label>/ 구조 유지
RENAME_BY_SHA = True                # True: 복사본 파일명을 sha256로 리네임
RENAME_EXT = ".exe"                 # 리네임 시 붙일 확장자
ENFORCE_NO_LEAKS = True             # 동일 sha가 여러 split에 있으면 한 split만 선택
SPLIT_PRIORITY = ["train", "val", "test"]  # 누수 시 우선 순위
# ===============================================

# 패커 섹션명 힌트
PACKER_HINT_NAMES = (b"UPX", b"MPRESS", b"ASPACK", b"kkrunchy", b"themida", b"petite", b"mpress")
# Machine 상수
MACHINE_I386  = 0x014c
MACHINE_AMD64 = 0x8664


def sniff_split(path: str) -> str:
    """
    경로 세그먼트가 'train', 'val(valid/validation)', 'test(testing)'로
    '시작'만 해도 인식하도록 완화. (예: Train_420 -> train)
    """
    p = path.lower().replace("\\", "/")
    parts = [seg for seg in p.split("/") if seg]
    for comp in reversed(parts):
        c = comp.strip()
        if c in ("train",):
            return "train"
        if c in ("val", "valid", "validation"):
            return "val"
        if c in ("test", "testing"):
            return "test"
        if c.startswith("train"):
            return "train"
        if c.startswith(("val", "valid", "validation")):
            return "val"
        if c.startswith(("test", "testing")):
            return "test"
    return ""


def sniff_label(path: str) -> Tuple[int, str]:
    p = path.lower()
    if "malware" in p:
        return 1, "malware"
    if "normal" in p or "benign" in p or "clean" in p:
        return 0, "normal"
    return -1, ""


def is_hidden_name(name: str) -> bool:
    base = os.path.basename(name)
    return any(base.startswith(pref) for pref in HIDDEN_NAME_PREFIXES)


def file_sha256(path: str, buf=1024*1024) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            b = f.read(buf)
            if not b: break
            h.update(b)
    return h.hexdigest()


def entropy_bytes(data: bytes) -> float:
    if not data:
        return -1.0
    counts = [0]*256
    for b in data:
        counts[b] += 1
    total = len(data)
    ent = 0.0
    for c in counts:
        if c:
            p = c/total
            ent -= p*math.log2(p)
    return ent


def entropy_of_file(path: str, max_bytes=MAX_BYTES_FOR_ENTROPY) -> float:
    size = os.path.getsize(path)
    to_read = size if (max_bytes is None) else min(size, max_bytes)  # ✅ 전체 사용 or 상한
    if to_read <= 0:
        return -1.0
    read = 0
    counts = [0]*256
    with open(path, "rb") as f:
        while read < to_read:
            chunk = f.read(min(1024*1024, to_read - read))  # 1MB 스트리밍
            if not chunk:
                break
            read += len(chunk)
            for b in chunk:
                counts[b] += 1
    if read == 0:
        return -1.0
    ent = 0.0
    for c in counts:
        if c:
            p = c/read
            ent -= p*math.log2(p)
    return ent


def parse_pe_and_sections(path: str, max_section_bytes=2*1024*1024):
    """
    강화된 PE 파서:
    - MZ/PE 확인
    - PE32/PE32+ Magic
    - Characteristics로 DLL 여부
    - SizeOfHeaders/섹션 포인터 정합성
    - 섹션 포인터 범위/겹침
    - 섹션 엔트로피/패커 섹션명 힌트
    """
    info = dict(
        pe_valid=False, machine=-1, num_sections=-1, magic=-1,
        characteristics=0, is_dll=0, size_of_headers=-1,
        pointer_sanity_ok=0, ptr_oob_sections=0, overlap_sections=0,
        section_entropy_mean=-1.0, section_entropy_max=-1.0, high_entropy_sections=0,
        packer_name_hint="", packer_name_hit=0
    )
    try:
        fsz = os.path.getsize(path)
        with open(path, "rb") as f:
            if f.read(2) != b"MZ":
                return info
            f.seek(0x3C)
            pe_off_b = f.read(4)
            if len(pe_off_b) < 4:
                return info
            pe_off = int.from_bytes(pe_off_b, "little", signed=False)
            f.seek(pe_off)
            if f.read(4) != b"PE\x00\x00":
                return info

            # COFF
            coff = f.read(20)
            if len(coff) < 20:
                return info
            (machine, num_sections, _ts, _ptrsym, _numsym, size_opt, characteristics) = struct.unpack("<HHIIIHH", coff)
            info["machine"] = machine
            info["num_sections"] = num_sections
            info["characteristics"] = characteristics
            info["is_dll"] = 1 if (characteristics & 0x2000) else 0  # IMAGE_FILE_DLL

            # Optional header
            opt_pos = f.tell()
            magic = struct.unpack("<H", f.read(2))[0]
            info["magic"] = magic
            # SizeOfHeaders: +0x3C
            f.seek(opt_pos + 0x3C)
            soh_b = f.read(4)
            if len(soh_b) == 4:
                info["size_of_headers"] = int.from_bytes(soh_b, "little", signed=False)
            f.seek(opt_pos + size_opt)  # 섹션 테이블로

            ranges = []
            section_ents = []
            packer_hit = ""
            first_ptr = None

            for _ in range(num_sections):
                sh = f.read(40)
                if len(sh) < 40:
                    break
                name, vsize, vaddr, size_raw, ptr_raw, *_ = struct.unpack("<8sIIIIIIHHI", sh)
                up = name.strip(b"\x00")
                if any(h in up for h in PACKER_HINT_NAMES):
                    packer_hit = up.decode(errors="ignore")

                if size_raw > 0 and ptr_raw > 0:
                    if first_ptr is None or ptr_raw < first_ptr:
                        first_ptr = ptr_raw
                    end = ptr_raw + size_raw
                    ranges.append((ptr_raw, end))
                    # 섹션 엔트로피
                    try:
                        with open(path, "rb") as sf:
                            sf.seek(ptr_raw)
                            data = sf.read(min(size_raw, max_section_bytes))
                            ent = entropy_bytes(data)
                            if ent >= 0:
                                section_ents.append(ent)
                    except:
                        pass

            # 범위/겹침 검증
            ptr_oob = 0
            for s, e in ranges:
                if s < 0 or e < 0 or s > fsz or e > fsz or s >= e:
                    ptr_oob += 1
            info["ptr_oob_sections"] = ptr_oob

            overlap = 0
            rs = sorted(ranges)
            for i in range(1, len(rs)):
                ps, pe = rs[i-1]
                cs, ce = rs[i]
                if cs < pe:
                    overlap += 1
            info["overlap_sections"] = overlap

            if info["size_of_headers"] > 0 and (first_ptr is not None):
                info["pointer_sanity_ok"] = 1 if first_ptr >= info["size_of_headers"] else 0

            if section_ents:
                info["section_entropy_mean"] = sum(section_ents)/len(section_ents)
                info["section_entropy_max"]  = max(section_ents)
                info["high_entropy_sections"] = sum(1 for e in section_ents if e >= HIGH_ENTROPY_THRESH)

            if packer_hit:
                info["packer_name_hint"] = packer_hit
                info["packer_name_hit"]  = 1

            info["pe_valid"] = True
            return info
    except:
        return info


def ensure_dir(p: str):
    os.makedirs(p, exist_ok=True)


def pct(x, n):
    return 0.0 if n == 0 else round(100.0 * x / n, 1)


def materialize_clean_set(rows, clean_root: str):
    """eligible 행을 기준으로 정제본 EXE 복사본 생성."""
    if not clean_root:
        return 0, 0

    ensure_dir(clean_root)

    # 누수 제거(동일 sha가 여러 split에 있으면 하나만 선택)
    selected = []
    if ENFORCE_NO_LEAKS:
        by_sha = defaultdict(list)
        for r in rows:
            if r["eligible"] == 1 and r["sha256"]:
                by_sha[r["sha256"]].append(r)

        for sha, items in by_sha.items():
            if len(items) == 1:
                selected.append(items[0])
            else:
                # 우선순위 split 선택
                best = None
                for sp in SPLIT_PRIORITY + [""]:
                    cand = [x for x in items if (x["split"] or "") == sp]
                    if cand:
                        best = cand[0]; break
                selected.append(best)
    else:
        selected = [r for r in rows if r["eligible"] == 1]

    copied, errors = 0, 0
    for r in selected:
        try:
            src = r["path"]
            if not os.path.isfile(src):
                continue

            # 대상 디렉토리
            split = r["split"] or "unsplit"
            label = r["label_name"] or ("label_"+str(r["label"]))
            if PRESERVE_STRUCTURE:
                dst_dir = os.path.join(clean_root, split, label)
            else:
                dst_dir = os.path.join(clean_root, label)
            ensure_dir(dst_dir)

            # 파일명
            if RENAME_BY_SHA and r["sha256"]:
                stem = r["sha256"]
                fname = stem + RENAME_EXT
            else:
                fname = os.path.basename(src)

            dst = os.path.join(dst_dir, fname)
            # 충돌 방지
            base, ext = os.path.splitext(dst)
            i = 1
            while os.path.exists(dst):
                dst = f"{base}_{i}{ext}"
                i += 1

            shutil.copy2(src, dst)
            copied += 1
        except Exception as e:
            errors += 1
            print(f"[복사 에러] {r.get('path','<unknown>')} -> {dst_dir} ({e})")

    return copied, errors


def _guard_clean_root():
    """CLEAN_ROOT가 INPUT_ROOTS 내부에 포함되는 실수를 방지"""
    if not CLEAN_ROOT:
        return
    cr = os.path.abspath(CLEAN_ROOT)
    for src in INPUT_ROOTS:
        if os.path.commonpath([cr, os.path.abspath(src)]) == os.path.abspath(src):
            raise ValueError("CLEAN_ROOT는 INPUT_ROOTS 바깥 경로로 지정하세요.")


def convert_exe_to_grayscale(source_path, destination_path):
    """
    Converts executable files to grayscale images without resizing.

    Args:
        source_path (str): The path to the folder containing the executable files.
        destination_path (str): The path to the folder where the grayscale images will be saved.
    """
    if not os.path.exists(destination_path):
        os.makedirs(destination_path)

    print(f"Converting EXEs from {source_path} to grayscale images in {destination_path}")

    for filename in os.listdir(source_path):
        file_path = os.path.join(source_path, filename)
        if os.path.isfile(file_path):
            try:
                with open(file_path, 'rb') as f:
                    byte_data = f.read()

                # Convert byte data to grayscale image
                # Each byte is treated as a pixel value (0-255)
                # The image width will be the square root of the number of bytes,
                # rounded up, to accommodate all bytes.
                num_bytes = len(byte_data)
                width = int(np.ceil(np.sqrt(num_bytes)))
                height = width # Make it a square image

                # Pad the byte data with zeros if necessary to make it fit the square image
                padding = (width * height) - num_bytes
                padded_data = byte_data + b'\x00' * padding

                image = Image.frombytes('L', (width, height), padded_data)

                # Save the grayscale image
                image_filename = os.path.splitext(filename)[0] + '.png'
                image_path = os.path.join(destination_path, image_filename)
                image.save(image_path)
                # print(f"Converted {filename} to {image_filename}") # Reduced verbosity

            except Exception as e:
                print(f"Error converting {filename}: {e}")


def resize_images_in_directory(source_dir: Path, dest_dir: Path, target_size: tuple):
    """
    주어진 소스 디렉토리의 모든 하위 폴더를 탐색하여 이미지 파일을 찾고,
    지정된 크기로 조정한 후 대상 디렉토리에 동일한 구조로 저장합니다.
    """
    processed_count = 0
    skipped_count = 0

    print(f"Resizing images from: {source_dir} to {target_size}")
    print(f"Saving resized images to: {dest_dir}")


    for class_dir in source_dir.iterdir():
        if class_dir.is_dir():
            class_name = class_dir.name
            dest_class_dir = dest_dir / class_name
            dest_class_dir.mkdir(parents=True, exist_ok=True)
            # print(f"클래스 '{class_name}' 처리 중...") # Reduced verbosity

            for img_path in class_dir.glob('*'):
                if img_path.is_file() and img_path.suffix.lower() in ['.png', '.jpg', '.jpeg', '.bmp', '.gif']: # 이미지 파일 확장자 확인
                    dest_img_path = dest_class_dir / img_path.name

                    # 이미 파일이 존재하면 건너뛰기
                    if dest_img_path.exists():
                        skipped_count += 1
                        continue

                    try:
                        with Image.open(img_path) as img:
                            # 이미지가 RGB 모드가 아니면 변환
                            if img.mode != 'RGB':
                                img = img.convert('RGB')

                            # 이미지 크기 조정
                            img_resized = img.resize(target_size)

                            # 크기 조정된 이미지 저장 (PNG 형식으로 통일)
                            img_resized.save(dest_img_path, 'PNG')
                            processed_count += 1
                            # 진행 상황 표시 (예: 100개 처리될 때마다 출력)
                            if processed_count > 0 and processed_count % 100 == 0:
                                print(f"  {processed_count}개 이미지 처리됨...")

                    except Exception as e:
                        print(f"오류 발생 - 파일: {img_path}, 오류: {e}")
                        # 오류 발생 시 해당 파일은 건너뜠니다.
                        continue

    print(f"\n✅ 이미지 크기 조정 완료.")
    print(f"처리된 이미지 수: {processed_count}")
    print(f"이미 존재하여 건너뛴 이미지 수: {skipped_count}")


def main():
    if not INPUT_ROOTS:
        raise ValueError("INPUT_ROOTS를 1개 이상 지정하세요.")
    _guard_clean_root()

    seen_hash = set()
    rows = []
    stats = defaultdict(int)

    # ================== 1. Preprocessing ==================
    print("=== Starting Preprocessing ===")
    for root_dir in INPUT_ROOTS:
        if not os.path.isdir(root_dir):
            print(f"[경고] 디렉토리 아님/없음: {root_dir}")
            continue

        for r, _dirs, files in os.walk(root_dir):
            for fn in files:
                fp = os.path.join(r, fn)
                try:
                    # 파일성/링크/숨김 필터
                    if not os.path.isfile(fp):
                        continue
                    if FILTER_SYMLINKS and os.path.islink(fp):
                        stats["symlink_filtered"] += 1; continue
                    if FILTER_HIDDEN_FILES and is_hidden_name(fp):
                        stats["hidden_filtered"] += 1; continue

                    size = os.path.getsize(fp)
                    split = sniff_split(r)
                    label, label_name = sniff_label(r)

                    invalid_reason = ""
                    duplicate = 0

                    # 크기 필터(+ 0바이트 차단)
                    if size <= 0:
                        invalid_reason = "size_zero"
                    elif size < MIN_SIZE_BYTES:
                        invalid_reason = f"too_small<{MIN_SIZE_BYTES}"
                    elif (MAX_SIZE_BYTES is not None) and (size > MAX_SIZE_BYTES):
                        invalid_reason = f"too_large>{MAX_SIZE_BYTES}"

                    # sha256 & 중복
                    sha = file_sha256(fp)
                    if not invalid_reason:
                        if SKIP_DUPLICATES and sha in seen_hash:
                            duplicate = 1
                            invalid_reason = "duplicate_sha256"
                        else:
                            seen_hash.add(sha)

                    # 전체 엔트로피 (파일 전체 또는 상한까지)
                    overall_ent = -1.0
                    if not invalid_reason:
                        overall_ent = entropy_of_file(fp, MAX_BYTES_FOR_ENTROPY)

                    # PE 파싱
                    pe = dict(pe_valid=False, machine=-1, num_sections=-1, magic=-1,
                              characteristics=0, is_dll=0, size_of_headers=-1,
                              pointer_sanity_ok=0, ptr_oob_sections=0, overlap_sections=0,
                              section_entropy_mean=-1.0, section_entropy_max=-1.0,
                              high_entropy_sections=0, packer_name_hint="", packer_name_hit=0)
                    if not invalid_reason:
                        pe = parse_pe_and_sections(fp)

                    # DLL 정책
                    if not invalid_reason and pe.get("is_dll", 0) and not ALLOW_DLLS:
                        invalid_reason = "dll_blocked"

                    # 패킹 의심
                    is_packed_heur = 1 if (
                        (overall_ent >= HIGH_ENTROPY_THRESH) or
                        (pe.get("high_entropy_sections", 0) > 0) or
                        (pe.get("packer_name_hit", 0) == 1)
                    ) else 0

                    # 유효성: 모든 조건 충족 + (REQUIRE_PE면 PE여야 함) + 섹션 포인터 이상 없음
                    is_valid = (invalid_reason == "") \
                               and (pe.get("pe_valid", False) if REQUIRE_PE else True) \
                               and (pe.get("ptr_oob_sections", 0) == 0) \
                               and (pe.get("overlap_sections", 0) == 0)

                    row = {
                        "sha256": sha,
                        "path": fp,
                        "split": split,
                        "label": label,
                        "label_name": label_name,
                        "size": size,
                        "overall_entropy": round(overall_ent, 6) if overall_ent >= 0 else -1.0,
                        "is_pe": int(pe.get("pe_valid", False)),
                        "magic": pe.get("magic", -1),
                        "machine": pe.get("machine", -1),
                        "num_sections": pe.get("num_sections", -1),
                        "size_of_headers": pe.get("size_of_headers", -1),
                        "pointer_sanity_ok": pe.get("pointer_sanity_ok", 0),
                        "ptr_oob_sections": pe.get("ptr_oob_sections", 0),
                        "overlap_sections": pe.get("overlap_sections", 0),
                        "is_dll": pe.get("is_dll", 0),
                        "section_entropy_mean": round(pe.get("section_entropy_mean", -1.0), 6),
                        "section_entropy_max": round(pe.get("section_entropy_max", -1.0), 6),
                        "high_entropy_sections": pe.get("high_entropy_sections", 0),
                        "packer_name_hint": pe.get("packer_name_hint", ""),
                        "packer_name_hit": pe.get("packer_name_hit", 0),
                        "is_packed_heur": is_packed_heur,
                        "duplicate": duplicate,
                        "invalid_reason": invalid_reason if invalid_reason else (
                            "not_pe" if (REQUIRE_PE and not pe.get("pe_valid", False)) else ""
                        ),
                        "eligible": int(is_valid)
                    }
                    rows.append(row)

                    # 통계
                    stats["total"] += 1
                    if duplicate: stats["duplicates"] += 1
                    if row["invalid_reason"]: stats["invalid"] += 1
                    if is_valid: stats["eligible"] += 1

                except Exception as e:
                    stats["errors"] += 1
                    rows.append({
                        "sha256": "",
                        "path": fp,
                        "split": sniff_split(r),
                        "label": -1, "label_name": "",
                        "size": -1,
                        "overall_entropy": -1.0,
                        "is_pe": 0, "magic": -1, "machine": -1, "num_sections": -1,
                        "size_of_headers": -1, "pointer_sanity_ok": 0,
                        "ptr_oob_sections": 0, "overlap_sections": 0,
                        "is_dll": 0,
                        "section_entropy_mean": -1.0, "section_entropy_max": -1.0,
                        "high_entropy_sections": 0, "packer_name_hint": "", "packer_name_hit": 0,
                        "is_packed_heur": 0,
                        "duplicate": 0, "invalid_reason": f"exception:{e}", "eligible": 0
                    })

    # 누수(동일 sha가 여러 split)에 대한 리포트
    hash_to_splits = defaultdict(set)
    for r in rows:
        if r["sha256"] and r["split"]:
            hash_to_splits[r["sha256"]].add(r["split"])
    leaks = [(h, sorted(list(s))) for h, s in hash_to_splits.items() if len(s) > 1]

    # CSV 저장
    fieldnames = [
        "sha256","path","split","label","label_name","size",
        "overall_entropy","is_pe","magic","machine","num_sections",
        "size_of_headers","pointer_sanity_ok","ptr_oob_sections","overlap_sections",
        "is_dll","section_entropy_mean","section_entropy_max","high_entropy_sections",
        "packer_name_hint","packer_name_hit","is_packed_heur",
        "duplicate","invalid_reason","eligible"
    ]
    with open(OUT_CSV, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for r in rows:
            w.writerow(r)

    # 설정(JSON) 저장(재현성)
    cfg = {
        "created_at": time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()),
        "platform": platform.platform(),
        "python": platform.python_version(),
        "input_roots": INPUT_ROOTS,
        "filters": {
            "min_size": MIN_SIZE_BYTES, "max_size": MAX_SIZE_BYTES,
            "require_pe": REQUIRE_PE, "allow_dlls": ALLOW_DLLS,
            "filter_symlinks": FILTER_SYMLINKS, "filter_hidden_files": FILTER_HIDDEN_FILES,
            "hidden_prefixes": HIDDEN_NAME_PREFIXES
        },
        "entropy": {
            "max_bytes_for_entropy": MAX_BYTES_FOR_ENTROPY,
            "high_entropy_thresh": HIGH_ENTROPY_THRESH
        },
        "dedup": {"skip_duplicates": SKIP_DUPLICATES},
        "clean_root": CLEAN_ROOT,
        "preserve_structure": PRESERVE_STRUCTURE,
        "rename_by_sha": RENAME_BY_SHA,
        "rename_ext": RENAME_EXT,
        "enforce_no_leaks": ENFORCE_NO_LEAKS,
        "split_priority": SPLIT_PRIORITY,
        "output_csv": OUT_CSV
    }
    with open(OUT_CFG, "w", encoding="utf-8") as f:
        json.dump(cfg, f, ensure_ascii=False, indent=2)

    # 정제본 복사본 생성
    copied, copy_errors = 0, 0
    if CLEAN_ROOT:
        copied, copy_errors = materialize_clean_set(rows, CLEAN_ROOT)

    # 요약 출력
    print("=== Preprocessing Summary ===")
    print(f"Total files: {stats.get('total',0)}")
    print(f"Eligible: {stats.get('eligible',0)}")
    print(f"Excluded (too_small/too_large/not_pe/duplicate/dll_blocked etc.): {stats.get('invalid',0)}")
    print(f"Duplicates (sha256): {stats.get('duplicates',0)}")
    print(f"Hidden filter: {stats.get('hidden_filtered',0)} | symlink filter: {stats.get('symlink_filtered',0)}")
    print(f"Errors: {stats.get('errors',0)}")
    print(f"CSV saved to: {OUT_CSV}")
    print(f"CONFIG saved to: {OUT_CFG}")
    if CLEAN_ROOT:
        print(f"Clean copy: Success {copied}, Errors {copy_errors} -> {CLEAN_ROOT}")

    if leaks:
        print(f"\n⚠️ Cross-split leak suspicion {len(leaks)} cases (same sha exists in multiple splits):")
        for h, s in leaks[:10]:
            print(f"- {h[:12]}... in {s}")
        if len(leaks) > 10:
            print(f"... (Total {len(leaks)} cases)")
        if ENFORCE_NO_LEAKS and CLEAN_ROOT:
            print("  → When copying clean versions, only one split was kept according to priority.")
    else:
        print("\n✅ No cross-split leaks")

    # Bias/Distribution Report
    print("\n=== Distribution Report (eligible, by split) ===")
    by_split = defaultdict(list)
    for r in rows:
        if r["eligible"] == 1:
            by_split[r["split"]].append(r)
    for split in ["train", "val", "test", ""]:
        items = by_split.get(split, [])
        if not items: continue
        n = len(items)
        c_label = Counter([r["label_name"] for r in items])
        packed = sum(1 for r in items if r.get("is_packed_heur",0))
        dlls   = sum(1 for r in items if r.get("is_dll",0))
        amd64  = sum(  1 for r in items if r.get("machine",-1) == MACHINE_AMD64)
        i386   = sum(1 for r in items if r.get("machine",-1) == MACHINE_I386)
        name = split or "unsplit"
        print(f"- {name}: {n} files | Label distribution={dict(c_label)} | packed≈{pct(packed,n)}% | DLL={pct(dlls,n)}% | AMD64={pct(amd64,n)}% | I386={pct(i386,n)}%")

    # ================== 2. EXE to Grayscale Image Conversion ==================
    print("\n=== Starting EXE to Grayscale Image Conversion ===")
    if CLEAN_ROOT:
        GRAYSCALE_DESTINATION_ROOT = "/content/drive/MyDrive/Fit_Bool/Static_image/7. POC2_민성/Gray_Scale_img/Test/Malware" # Update this path as needed
        # We need to iterate through the splits and labels within CLEAN_ROOT
        for split_dir in Path(CLEAN_ROOT).iterdir():
            if split_dir.is_dir():
                split_name = split_dir.name
                for label_dir in split_dir.iterdir():
                    if label_dir.is_dir():
                        label_name = label_dir.name
                        source_path = label_dir # Path to the directory containing EXEs for this split/label
                        destination_path = Path(GRAYSCALE_DESTINATION_ROOT) / split_name / label_name
                        convert_exe_to_grayscale(str(source_path), str(destination_path))
    else:
        print("CLEAN_ROOT is not set. Skipping EXE to grayscale conversion.")

    # ================== 3. Grayscale Image Resizing ==================
    print("\n=== Starting Grayscale Image Resizing ===")
    # Update these paths based on where the grayscale images were saved
    RESIZE_SOURCE_PATH = Path("/content/drive/MyDrive/Fit_Bool/Static_image/7. POC2_민성/Gray_Scale_img/Test/Malware") # Source is the output of the grayscale conversion
    RESIZE_DESTINATION_PATH = Path("/content/drive/MyDrive/Fit_Bool/Static_image/7. POC2_민성/Gray_Scale_img/Test_resizing_img") # Update this path as needed
    TARGET_SIZE = (256, 256) # Target image size

    if RESIZE_SOURCE_PATH.exists():
      RESIZE_DESTINATION_PATH.mkdir(parents=True, exist_ok=True)
      resize_images_in_directory(RESIZE_SOURCE_PATH, RESIZE_DESTINATION_PATH, TARGET_SIZE)
    else:
        print(f"Source directory for resizing not found: {RESIZE_SOURCE_PATH}. Skipping resizing.")


if __name__ == "__main__":
    main()