# -*- coding: utf-8 -*-
"""model_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14fgab98HqD6nt8f68oDUbK0iniPDssRx
"""

from tensorflow import keras
from pathlib import Path

def load_model(model_path: str):
    p = Path(model_path)
    if not p.exists():
        raise FileNotFoundError(f"Model not found: {p}")
    return keras.models.load_model(p)