# -*- coding: utf-8 -*-
"""inference_predict_cli.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RmYmFoHAldYjHaY7LrKYkyVnjqKS2c8Y
"""

# inference/predict_cli.py
import argparse, os, math, hashlib, tempfile
from pathlib import Path
from PIL import Image
import numpy as np

from inference.model_loader import load_model

# ---------------- Utility ----------------
def is_pe(path: Path) -> bool:
    try:
        with open(path, "rb") as f:
            if f.read(2) != b"MZ":
                return False
            f.seek(0x3C)
            pe_off = int.from_bytes(f.read(4), "little", signed=False)
            f.seek(pe_off)
            return f.read(4) == b"PE\x00\x00"
    except:
        return False

def sha256(p: Path, buf=1024*1024):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        while True:
            b = f.read(buf)
            if not b: break
            h.update(b)
    return h.hexdigest()

def exe_to_gray_png(exe_path: Path, out_png: Path):
    with open(exe_path, "rb") as f:
        data = f.read()
    n = len(data)
    w = int(math.ceil(math.sqrt(n)))
    h = w
    pad = (w*h) - n
    if pad > 0:
        data = data + b"\x00"*pad
    img = Image.frombytes("L", (w, h), data)
    out_png.parent.mkdir(parents=True, exist_ok=True)
    img.save(out_png, "PNG")
    return out_png

def resize_png(src_png: Path, dst_png: Path, size=(256,256)):
    with Image.open(src_png) as img:
        if img.mode != "RGB":
            img = img.convert("RGB")
        img = img.resize(size)
        dst_png.parent.mkdir(parents=True, exist_ok=True)
        img.save(dst_png, "PNG")
    return dst_png

def load_png_as_tensor(png_path: Path, size=(256,256)):
    with Image.open(png_path) as img:
        if img.mode != "RGB":
            img = img.convert("RGB")
        img = img.resize(size)
        arr = np.array(img, dtype=np.float32) / 255.0
        return np.expand_dims(arr, axis=0)

# ---------------- Process & Predict ----------------
def process_upload_and_predict(exe_path: Path, model_path: Path, size=(256,256)):
    # 임시 작업 디렉토리
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        gray_png = td / "gray.png"
        resized_png = td / "resized.png"

        # 1) 간단 전처리
        if exe_path.stat().st_size < 1024:
            raise RuntimeError("File too small")
        if not is_pe(exe_path):
            raise RuntimeError("Not a valid PE executable")

        # 2) Grayscale 변환
        exe_to_gray_png(exe_path, gray_png)

        # 3) 리사이즈
        resize_png(gray_png, resized_png, size=size)

        # 4) 텐서 변환
        x = load_png_as_tensor(resized_png, size=size)

        # 5) 모델 로드 및 추론
        model = load_model(model_path)
        prob = float(model.predict(x, verbose=0)[0].squeeze())
        label = "MALWARE" if prob >= 0.5 else "NORMAL"
        return label, prob

# ---------------- CLI Entry ----------------
def main():
    ap = argparse.ArgumentParser(description="EXE → Preprocess+Predict")
    ap.add_argument("--exe", required=True, help="EXE 파일 경로")
    ap.add_argument("--model", default="models/base_cnn.keras", help="학습된 모델 경로")
    ap.add_argument("--size", default="256,256", help="리사이즈 크기 (w,h)")
    args = ap.parse_args()

    size = tuple(map(int, args.size.split(",")))
    label, prob = process_upload_and_predict(Path(args.exe), Path(args.model), size=size)
    print(f"Prediction: {label} (prob={prob:.4f})")

if __name__ == "__main__":
    main()